name: events-trigger-example
on:
    push:
        branches:
          - main
jobs:
    JBname:
        runs-on: ubuntu-latest
        steps:
          - name: check the job is running
            run: echo "hi  job is running "