name: events-trigger-example

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "* * * * *"
concurrency:
  group: my-group
  cancel-in-progress: true
jobs:
    JBname:
        runs-on: ubuntu-latest
        steps:
            - name: check the job is running
              run: echo "hi  job is running "
            - name: check the job is running
              run: echo "hi  job is running "
            - name: check the job is running
              run: echo "hi  job is running "
            - name: check the job is running
              run: echo "hi  job is running "
            - name: check the job is running
              run: echo "hi  job is running "
    JBname2:
        runs-on: ubuntu-latest
        steps:
            - name: check the job is running
              run: echo "hi  job is running "
            - name: check the job is running
              run: echo "hi  job is running "
            - name: check the job is running
              run: echo "hi  job is running "
            - name: check the job is running
              run: echo "hi  job is running "
