name: upload-download example
on :
    workflow_dispatch:
env:
    filename: Data.txt
jobs:
    example:
        runs-on: ubuntu-latest
        steps:
          - name: upload example
            run: echo "hi $ filename">data.txt
          - name: upload example
            uses: actions/upload-artifact@v4
            with:
               name: dataFile
               path: data.txt
    example2:
        runs-on: ubuntu-latest
        needs: example
        steps:
          - name: example2 runner
            run : echo "hi i am runner 2 example 2"
          -  name: download files
             uses: actions/download-artifact@v4
             with:
                name: dataFile
          -  name: Show file content
             run: cat data.txt



 
