name: variables example
on :
 workflow_dispatch:

env:
  City: Ap
jobs:
  Varaibles_example_stepLevel :
     runs-on: ubuntu-latest
     steps:

       - name: smaple runnering
         env:
            CITY : Delhi
         run: echo "HI $CITY"
       - name: smaple runnering2
         run: echo 'hi i am sample runnering2'
  variables_example_JobLevel:
        needs: Varaibles_example_stepLevel
     
        runs-on: ubuntu-latest
        env:
          CITY: Dubai
        steps:
          - name: runner smaple job level variable cheking
            run: echo "runner smaple job level variable cheking"
          - name: runner smaple check job level variable 
            run: echo "Hi $CITY"
  check_level: 
    needs:  variables_example_JobLevel
    runs-on: ubuntu-latest
    steps:
      - name: JOb level variable checking
        run: echo "Job level variable checking"
      - name: JOb level variable checking
        run: echo "Job level variable $CITY"



  
         
       
  
