name: variables example
on :
 workflow_dispatch:
jobs:
  Varaibles_example :
     runs-on: ubuntu-latest

     steps:
       - name: smaple runnering
         run: echo 'hi i am sample runnering'
       - name: smaple runnering2
         run: echo 'hi i am sample runnering2'
         
       
  
